# same as the placeholder used by hms-system
TEMPLATE_REGISTRATION = "Thank you for registering with Hospital Management System."
TEMPLATE_APPOINTMENT_BOOKING_PENDING = "Your appointment request has been received and is pending approval."
TEMPLATE_APPOINTMENT_BOOKING_CONFIRMED = "Your appointment has been confirmed."
TEMPLATE_APPOINTMENT_APPROVED = "Your appointment request has been approved."
TEMPLATE_APPOINTMENT_CANCELLED = "Your appointment has been cancelled."
TEMPLATE_CONSULTATION_COMPLETE = "Your consultation is complete. Thank you."
TEMPLATE_PRESCRIPTION_READY = "Your prescription is ready for pickup."
TEMPLATE_LAB_RESULTS_READY = "Your lab results are ready."
TEMPLATE_MEDICAL_RECORDS_AVAILABLE = "Your medical records are now available."
TEMPLATE_PAYMENT_REMINDER = "Reminder: please settle your outstanding payment."
TEMPLATE_APPOINTMENT_REMINDER = "Reminder: you have an upcoming appointment."
TEMPLATE_DISCHARGE_SUMMARY = "Your discharge summary is ready."
TEMPLATE_VACCINATION_RECORD = "Your vaccination record has been updated."
TEMPLATE_HEALTH_CHECKUP = "It's time for your periodic health checkup."
